version: '3'

services:
  app:
    build: .
    restart: on-failure
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql://postgres:qwer1234@db/postgres"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: qwer1234
    ports:
      - "5435:5432"
    env_file:
      - .env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data:cached

