version: '3.8'

services:
  artifactory:
    container_name: artifactory
    build: .
    ports:
      - "8081:8081"
      - "8082:8082"
    #volumes:
    #  - D:/ArtifacotryStore:/var/opt/jfrog/artifactory/data/artifactory/filestore
    restart: unless-stopped
  postgres:
    container_name: postgres
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: qwer1234
    restart: unless-stopped